{% set name = "inference-server" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inference_server-{{ version }}.tar.gz
  sha256: 08bc663404dbddb160b7cd8cf9f507b0baed8cd3271d66baf11c1f1f939a58ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - botocore
    - codetiming >=1.4,<2.dev0
    - orjson >=3.0,<4.dev0
    - pluggy >=1.0,<2.dev0
    - werkzeug >=2.0,<3.dev0

test:
  imports:
    - inference_server
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Deploy your AI/ML model to Amazon SageMaker for Real-Time Inference and Batch Transform using your own Docker container image.
  home: https://github.com/jpmorganchase/inference-server
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - faph
